color: null
fieldLayouts:
  1cecd51f-48a6-4af5-88a1-c92da236a7a5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-03T17:18:35+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2e76f355-4d58-4e52-8c3d-f13c8ec70a0a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-03T17:20:19+00:00'
            elementCondition: null
            fieldUid: 60eb3ca0-3216-4b6b-9c34-5e60570c8300 # Size
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: baac21c4-e2d6-4b4b-81bc-e952cdf77284
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-03T17:20:19+00:00'
            elementCondition: null
            fieldUid: aa10a5f2-b7f8-4b5c-a2f3-b1719e3924bd # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5193abcf-9385-4c18-ae14-3c711b1a52d6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 047ede4b-8b70-462e-8013-a298c7332427
        userCondition: null
handle: bannerItems
hasTitleField: false
icon: layer-group
name: 'Banner Items'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
