color: null
fieldLayouts:
  2dbdd9e9-da52-482a-8f23-d2d9fd064fe6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-03T07:51:41+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 21e267ea-5e70-4aa6-a5ee-1cfcb1ea8691
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-03T07:59:59+00:00'
            elementCondition: null
            fieldUid: 5d04f5b0-4271-45e5-bbb2-a410d01cae6e # Case Study Category
            handle: null
            includeInCards: false
            instructions: null
            label: Category
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 454a54bf-c246-484a-94e1-e92f4c32feb9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-03T07:59:59+00:00'
            elementCondition: null
            fieldUid: 52e92402-78f6-4f5a-96ff-af4f76fb213d # Matrix Blocks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 818b8ac4-d852-425f-b243-02ac479d1e53
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4ac3b198-7d0f-44eb-bfee-908d3d60b6dd
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-03T07:59:59+00:00'
            elementCondition: null
            fieldUid: aa10a5f2-b7f8-4b5c-a2f3-b1719e3924bd # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dad95062-1c77-4058-bde0-bfac00604feb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-03T07:59:59+00:00'
            elementCondition: null
            fieldUid: 09930591-33c2-442f-ab5f-b870f81381a3 # Video
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8845c01-b85e-4e8e-885e-dae69774772c
            userCondition: null
            warning: null
            width: 100
        name: Assets
        uid: 606f0b77-7cb4-4393-b39f-7c46b258b566
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-03T07:59:59+00:00'
            elementCondition: null
            fieldUid: 468b0e80-4386-4d5a-ab7e-e3bdc6218b6b # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b49e0e45-8e93-4ff8-ab1d-fa275bae9024
            userCondition: null
            warning: null
            width: 100
        name: Meta
        uid: 6169d736-8a3f-40ff-bf86-0ba4f3e01f4e
        userCondition: null
handle: casestudiesdefault
hasTitleField: true
icon: acorn
name: caseStudiesDefault
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
