color: null
fieldLayouts:
  ea46101e-d8d1-428b-997d-c258fc62b2a8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-03T07:38:16+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3cc45fcc-bad7-4596-86db-466c781b7d2c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-03T18:43:30+00:00'
            elementCondition: null
            fieldUid: ee10b0d3-a081-4859-8cdd-f84ce01cd6ec # Header
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e6ae31bb-23ef-4683-b10f-2197c35d233a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-03T07:39:51+00:00'
            elementCondition: null
            fieldUid: ac5452bf-ec8c-4014-8a63-a38aa45bddc5 # Button Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c89bdc7-f59b-4fa5-b52b-f0b8facf2c57
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-03T07:39:51+00:00'
            elementCondition: null
            fieldUid: 4ad38322-4f83-4460-b69f-5dc5dbe5b001 # Intro
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a1e4c89-987c-4ae4-9a3e-301582525346
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-03T07:39:51+00:00'
            elementCondition: null
            fieldUid: 09930591-33c2-442f-ab5f-b870f81381a3 # Video
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e26f8fb8-d1b3-4002-92d9-5817c7098752
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-03T07:39:51+00:00'
            elementCondition: null
            fieldUid: dcfc1d5b-c355-48e0-ad71-068b65cc8c7f # Background Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9661e6ca-0357-4064-9082-496045db7086
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3b3ac6c0-f7de-47ef-bb4b-7b16fb30af06
        userCondition: null
handle: heroVideo
hasTitleField: false
icon: video
name: 'Hero Video'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
