color: null
fieldLayouts:
  b891b161-447c-4919-be84-7d6a7be96df5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-03T17:19:31+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 074f3a9a-5db2-4787-9413-56c0843e1056
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-03T17:20:57+00:00'
            elementCondition: null
            fieldUid: 6d09286d-0d45-4e61-92f8-77bae9023475 # Banner Items
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 40d380f8-556f-4d0f-a138-52791ddd1122
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5c3a0f77-0a53-43b9-bedb-222b72e5bbd9
        userCondition: null
handle: imageBanner
hasTitleField: false
icon: flag-pennant
name: 'Image Banner'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
