color: null
fieldLayouts:
  6aa1a490-bdb2-4e21-82bf-e1b84b0345d9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-03T07:28:34+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6ed5e8fe-1664-4024-a361-6bb9138402b3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-03T17:29:27+00:00'
            elementCondition: null
            fieldUid: ee10b0d3-a081-4859-8cdd-f84ce01cd6ec # Header
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: efb0230e-fb91-4cd2-b2f8-3d612ac42c2d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-03T07:31:27+00:00'
            elementCondition: null
            fieldUid: ca8755a2-28e2-4d31-8a03-c90169c6cb3a # Body
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ffe7aa8-f7dd-4b81-9940-b009c656634c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 55a2d3ec-2bd5-4c8a-98bf-1adb15294baa
        userCondition: null
handle: interior
hasTitleField: false
icon: table-list
name: Interior
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{header}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
