baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Joey De Guzman'
primary: true
siteGroup: ec9342f3-446b-4408-a617-0b21d03406cb # joeydeguzman
sortOrder: 1
