columnSuffix: null
handle: matrixBlocks
instructions: null
name: 'Matrix Blocks'
searchable: true
settings:
  createButtonLabel: null
  entryTypes:
    - fd0285d9-3b57-4a7a-a93b-4f11d83810e9 # Hero Simple
    - 39726836-0f5d-40b0-8e1f-b1f26ab028e2 # Hero Split
    - 9432698d-2a29-495a-88f6-a66724150edb # Hero Video
    - 1fe6ecfa-c659-4370-8b8c-40ee0ca6e932 # Interior
    - b1288af3-0b51-4c7e-9a70-fa4301dbbb5a # Contact
    - ed062fe5-99f2-4d59-a5d8-710e4a6a190c # Featured Case Studies
    - 813355ea-98dd-4b4a-9564-ed8b022c5d34 # Case Studies
    - 5d51407f-bfae-4606-a891-0d72f09e4e41 # Single Case Study
    - 1445f16c-706d-4984-b85f-4882e962161d # Image Grid
    - ee02a333-e110-4380-94ee-10a5e40c1dce # Image Banner
    - a28b124b-4500-4ef4-8aad-7d809906c552 # SVG Grid
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: true
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
