columnSuffix: null
handle: size
instructions: null
name: Size
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Square
        -
          - value
          - square
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Wide
        -
          - value
          - wide
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
